## -*- encoding: utf-8 -*-
# This file was *autogenerated* from the file answer-3.sagetex.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2017 = Integer(2017); _sage_const_2016 = Integer(2016); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_100 = Integer(100); _sage_const_42 = Integer(42); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_20 = Integer(20); _sage_const_32 = Integer(32); _sage_const_36 = Integer(36)## This file (answer-3.sagetex.sage) was *autogenerated* from answer-3.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('answer-3', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
try:
 _st_.inline(_sage_const_0 , latex(factor(_sage_const_2016 )))
except:
 _st_.goboom(_sage_const_12 )
try:
 _st_.inline(_sage_const_1 , latex(factor(_sage_const_2017 )))
except:
 _st_.goboom(_sage_const_13 )
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(sin(x**_sage_const_2 ), _sage_const_0 , pi))
except:
 _st_.goboom(_sage_const_20 )
_st_.blockbegin()
try:
 var('k, n')
 f = sum(sin(k), k, _sage_const_1 , n)
except:
 _st_.goboom(_sage_const_32 )
_st_.blockend()
try:
 _st_.inline(_sage_const_2 , latex(f))
except:
 _st_.goboom(_sage_const_36 )
try:
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plot(f, _sage_const_0 , _sage_const_100 , color='red'))
except:
 _st_.goboom(_sage_const_42 )
_st_.endofdoc()
