## -*- encoding: utf-8 -*-
## This file (latex.sagetex.sage) was *autogenerated* from latex.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('latex', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.endofdoc()
